OutputDebugString_sink Class Reference
[Sinks]
Sink for sending a statement to Windows' OutputDebugString().
#include <fastformat/sinks/OutputDebugString.hpp>
Public Types
typedef OutputDebugString_sink class_type
This type.
Public Member Functions
OutputDebugString_sink ()
Constructs the instance.
class_type & write (int flags, size_t cchTotal, size_t numResults, ff_string_slice_t const *results)
Outputs the results, according to the given flags.
Detailed Description
Sink for sending a statement to Windows' OutputDebugString().
Examples:
examples/example.sink.OutputDebugString/example.sink.OutputDebugString.cpp.
Member Typedef Documentation
typedef OutputDebugString_sink class_type
This type.
Constructor & Destructor Documentation
OutputDebugString_sink () [inline]
Constructs the instance.
Member Function Documentation
class_type& write (int flags, size_t cchTotal, size_t numResults, ff_string_slice_t const * results) [inline]
Outputs the results, according to the given flags.
References fastformat::util::concat_slices(), fastformat::fastformat_getNewlineForPlatform(), fastformat::flags::ff_newLine, ff_string_slice_t::len, and ff_string_slice_t::ptr.
Referenced by fastformat::sinks::fmt_slices().
The documentation for this class was generated from the following file:
fastformat/sinks/OutputDebugString.hpp
FastFormat Library documentation © Matthew Wilson, 2006-2015