vectored_file_sink Class Reference
[Sinks]
Sink for translating a statement into iovec instructions.
#include <fastformat/sinks/vectored_file.hpp>
Public Types
typedef vectored_file_sink class_type
This type.
Public Member Functions
vectored_file_sink (int fh)
Constructs from a file handle.
vectored_file_sink (int fh, char const *delim)
Constructs from a file handle and a delimiter.
class_type & write (size_t numResults, ff_string_slice_t const *results, int flags)
Outputs the results, according to the given flags.
Detailed Description
Sink for translating a statement into iovec instructions.
Member Typedef Documentation
typedef vectored_file_sink class_type
This type.
Constructor & Destructor Documentation
vectored_file_sink (int fh) [inline, explicit]
Constructs from a file handle.
vectored_file_sink (int fh, char const * delim) [inline]
Constructs from a file handle and a delimiter.
Member Function Documentation
class_type& write (size_t numResults, ff_string_slice_t const * results, int flags) [inline]
Outputs the results, according to the given flags.
References fastformat::fastformat_getNewlineForPlatform(), fastformat::flags::ff_flush, fastformat::flags::ff_newLine, fastformat::flush(), ff_string_slice_t::len, and ff_string_slice_t::ptr.
Referenced by fastformat::sinks::fmt_slices().
The documentation for this class was generated from the following file:
fastformat/sinks/vectored_file.hpp
FastFormat Library documentation © Matthew Wilson, 2006-2015