WindowsConsole_sink Class Reference
[Sinks]
Sink for coloured output via Windows' console.
#include <fastformat/sinks/WindowsConsole.hpp>
Public Member Functions
WindowsConsole_sink (HANDLE hConsole, WORD textAttributes)
Constructs an instance of the sink.
WindowsConsole_sink (WindowsConsole_sink const &rhs)
Copy constructor.
WindowsConsole_sink & write (int flags, size_t cchTotal, size_t numResults, ff_string_slice_t const *results)
Coalesces the slices and write the result to the Windows' console.
Detailed Description
Sink for coloured output via Windows' console.
Constructor & Destructor Documentation
WindowsConsole_sink (HANDLE hConsole, WORD textAttributes) [inline]
Constructs an instance of the sink.
Parameters:
hConsole Handle of the console, or NULL to use the standard output handle.
textAttributes Text attributes to be used by the sink.
WindowsConsole_sink (WindowsConsole_sink const & rhs)
Copy constructor.
Member Function Documentation
WindowsConsole_sink& write (int flags, size_t cchTotal, size_t numResults, ff_string_slice_t const * results) [inline]
Coalesces the slices and write the result to the Windows' console.
References fastformat::util::concat_slices(), fastformat::fastformat_getNewlineForPlatform(), fastformat::flags::ff_newLine, ff_string_slice_t::len, and ff_string_slice_t::ptr.
Referenced by fastformat::sinks::fmt_slices().
The documentation for this class was generated from the following file:
fastformat/sinks/WindowsConsole.hpp
FastFormat Library documentation © Matthew Wilson, 2006-2015