char_buffer_sink Class Reference
[Sinks]
Sink for translating a statement into char_buffer instructions.
#include <fastformat/sinks/char_buffer.hpp>
Public Types
typedef char_buffer_sink class_type
This type.
typedef ff_char_t char_type
The character type.
typedef size_t size_type
The size type.
Public Member Functions
char_buffer_sink (size_type n, char_type *buffer)
Constructs from a character buffer.
template<size_t N>
char_buffer_sink (char_type(&ar)[N])
Constructs from a character array.
size_type size () const
The number of characters written to the sink.
size_type capacity () const
The total number of characters accessible to the sink.
class_type & write (size_type cchTotal, size_type numResults, ff_string_slice_t const *results, int flags)
Outputs the results, according to the given flags.
Detailed Description
Sink for translating a statement into char_buffer instructions.
Member Typedef Documentation
typedef ff_char_t char_type
The character type.
typedef char_buffer_sink class_type
This type.
typedef size_t size_type
The size type.
Constructor & Destructor Documentation
char_buffer_sink (size_type n, char_type * buffer) [inline]
Constructs from a character buffer.
char_buffer_sink (char_type(&) ar[N]) [inline]
Constructs from a character array.
Member Function Documentation
size_type capacity () const [inline]
The total number of characters accessible to the sink.
Referenced by char_buffer_sink::write().
size_type size () const [inline]
The number of characters written to the sink.
Referenced by char_buffer_sink::write().
class_type& write (size_type cchTotal, size_type numResults, ff_string_slice_t const * results, int flags) [inline]
Outputs the results, according to the given flags.
References char_buffer_sink::capacity(), fastformat::fastformat_getNewlineForPlatform(), fastformat::flags::ff_newLine, ff_string_slice_t::len, ff_string_slice_t::ptr, and char_buffer_sink::size().
Referenced by fastformat::sinks::fmt_slices().
The documentation for this class was generated from the following file:
fastformat/sinks/char_buffer.hpp
FastFormat Library documentation © Matthew Wilson, 2006-2015