shim_string_sink Class Reference
[Sinks]
This class acts as a sink for string shims, to be used with STLSoft 1.9.
#include <fastformat/sinks/shim_string.hpp>
Public Types
typedef shim_string_sink class_type
This type.
typedef
stlsoft::basic_shim_string
< ff_char_t > parent_class_type
The parent type.
typedef
parent_class_type::size_type size_type
The size type.
Public Member Functions
shim_string_sink ()
Constructs an empty instance.
shim_string_sink (size_type n)
Constructs an empty instance with the given capacity.
void reserve (size_type n)
Reserves the given capacity.
class_type & append (ff_char_t const *s, size_type n)
Appends part of a C-style string.
class_type & append (ff_char_t const *s)
appends a C-style string
void truncate (size_type n)
truncates the string
size_type size () const
The string size.
operator size_type () const
The string size.
Detailed Description
This class acts as a sink for string shims, to be used with STLSoft 1.9.
For example
  // in namespace mystuff
  class Thing
  {};
  // in namespace stlsoft
  inline shim_string_sink c_str_ptr_a(mystuff::Thing const& thing)
  {
    shim_string_sink  result;
    return result;
  }
Note:
This class is only necessary for STLSoft 1.9. If you're using STLSoft 1.10 (or the STLSoft 1.10 alpha in combination with STLSoft 1.9), then you can (and should!) just go ahead and use stlsoft::basic_shim_string.
Examples:
examples/example.overload.2.custom_type.string_access_shims/example.overload.2.custom_type.string_access_shims.cpp.
Member Typedef Documentation
typedef shim_string_sink class_type
This type.
typedef stlsoft::basic_shim_string<ff_char_t> parent_class_type
The parent type.
typedef parent_class_type::size_type size_type
The size type.
Constructor & Destructor Documentation
shim_string_sink () [inline]
Constructs an empty instance.
shim_string_sink (size_type n) [inline, explicit]
Constructs an empty instance with the given capacity.
Parameters:
n The required capacity
Member Function Documentation
class_type& append (ff_char_t const * s, size_type n) [inline]
Appends part of a C-style string.
Referenced by shim_string_sink::append().
class_type& append (ff_char_t const * s) [inline]
appends a C-style string
References shim_string_sink::append(), and fastformat::c_str_len().
operator size_type () const [inline]
The string size.
References shim_string_sink::size().
void reserve (size_type n) [inline]
Reserves the given capacity.
Parameters:
n The required capacity
size_type size () const [inline]
The string size.
Referenced by fastformat::sinks::c_str_len(), and shim_string_sink::operator size_type().
void truncate (size_type n) [inline]
truncates the string
The documentation for this class was generated from the following file:
fastformat/sinks/shim_string.hpp
FastFormat Library documentation © Matthew Wilson, 2006-2015