Sinks
[The FastFormat (C++) Application Layer]
Sink components, to allow output, via FastFormat write()/fmt() statements, to arbitrary types.
Classes
class c_string_sink
Sink for translating a statement into c_string instructions.
class char_buffer_sink
Sink for translating a statement into char_buffer instructions.
struct null_sink
A class that acts as a bit-bucket sink.
class OutputDebugString_sink
Sink for sending a statement to Windows' OutputDebugString().
class shim_string_sink
This class acts as a sink for string shims, to be used with STLSoft 1.9.
class speech_sink
Sink for translating a statement into speech.
class string_array_sink
Sink for translating a statement into an entry in an array of strings.
class vectored_file_sink
Sink for translating a statement into iovec instructions.
class WindowsConsole_sink
Sink for coloured output via Windows' console.
class WindowsMessageBox_sink
Sink for sending a statement to Windows' MessageBox().
Functions
ACE_CString & fmt_slices (ACE_CString &sink, int flags, size_t cchTotal, size_t numResults, ff_string_slice_t const *results)
Writes an array of string slices into a ACE_CString sink.
template<typename C , size_t N, typename A >
stlsoft::auto_buffer< C, N, A > & fmt_slices (stlsoft::auto_buffer< C, N, A > &sink, int flags, size_t cchTotal, size_t numResults, ff_string_slice_t const *results)
Formats into an auto_buffer.
CComBSTR & fmt_slices (CComBSTR &sink, int flags, size_t cchTotal, size_t numResults, ff_string_slice_t const *results)
Writes an array of string slices into a CComBSTR sink.
char_buffer_sink & fmt_slices (char_buffer_sink &sink, int flags, size_t cchTotal, size_t numResults, ff_string_slice_t const *results)
Formats into a char_buffer.
CString & fmt_slices (CString &sink, int flags, size_t cchTotal, size_t numResults, ff_string_slice_t const *results)
Writes an array of string slices into a CString sink.
FILE *& fmt_slices (FILE *&sink, int flags, size_t cchTotal, size_t numResults, ff_string_slice_t const *results)
Writes an array of string slices into a FILE* sink.
ff_FILE_sink & fmt_slices (ff_FILE_sink &sink, int flags, size_t cchTotal, size_t numResults, ff_string_slice_t const *results)
Writes an array of string slices into a ff_FILE_sink sink.
null_sink & fmt_slices (null_sink &sink, int, size_t cchTotal, size_t numResults, ff_string_slice_t const *results)
Writes an array of string slices into a null_sink sink.
std::basic_ostream< ff_char_t > & fmt_slices (std::basic_ostream< ff_char_t > &sink, int flags, size_t cchTotal, size_t numResults, ff_string_slice_t const *results)
Writes an array of string slices into a std::ostream sink.
OutputDebugString_sink & fmt_slices (OutputDebugString_sink &sink, int flags, size_t cchTotal, size_t numResults, ff_string_slice_t const *results)
Writes an array of string slices to Windows' OutputDebugString().
speech_sink & fmt_slices (speech_sink &sink, int flags, size_t cchTotal, size_t numResults, ff_string_slice_t const *results)
Writes an array of string slices into a speech sink.
string_array_sink & fmt_slices (string_array_sink &sink, int flags, size_t, size_t numResults, ff_string_slice_t const *results)
Writes an array of string slices into a string array sink.
std::basic_stringstream
< ff_char_t > & fmt_slices (std::basic_stringstream< ff_char_t > &sink, int flags, size_t, size_t numResults, ff_string_slice_t const *results)
Writes an array of string slices into a std::stringstream sink.
WindowsConsole_sink WindowsConsole (HANDLE hConsole, WORD textAttributes)
Creator function for the WindowsConsole_sink class.
WindowsConsole_sink WindowsConsole (WORD textAttributes)
Creator function for the WindowsConsole_sink class.
WindowsConsole_sink & fmt_slices (WindowsConsole_sink &sink, int flags, size_t cchTotal, size_t numResults, ff_string_slice_t const *results)
Writes an array of string slices into a WindowsConsole_sink sink.
WindowsMessageBox_sink MessageBox (HWND hwnd, LPCTSTR caption, UINT type)
Creator function for the WindowsMessageBox_sink class.
WindowsMessageBox_sink MessageBox (LPCTSTR caption, UINT type)
Creator function for the WindowsMessageBox_sink class.
WindowsMessageBox_sink & fmt_slices (WindowsMessageBox_sink &sink, int flags, size_t cchTotal, size_t numResults, ff_string_slice_t const *results)
Writes an array of string slices into a WindowsMessageBox_sink sink.
Detailed Description
Sink components, to allow output, via FastFormat write()/fmt() statements, to arbitrary types.
Function Documentation
ACE_CString& fastformat::sinks::fmt_slices (ACE_CString & sink, int flags, size_t cchTotal, size_t numResults, ff_string_slice_t const * results) [inline]
Writes an array of string slices into a ACE_CString sink.
References fastformat::util::concat_slices(), fastformat::fastformat_getNewlineForPlatform(), fastformat::flags::ff_newLine, ff_string_slice_t::len, and ff_string_slice_t::ptr.
WindowsMessageBox_sink& fastformat::sinks::fmt_slices (WindowsMessageBox_sink & sink, int flags, size_t cchTotal, size_t numResults, ff_string_slice_t const * results) [inline]
Writes an array of string slices into a WindowsMessageBox_sink sink.
References WindowsMessageBox_sink::write().
stlsoft::auto_buffer<C, N, A>& fastformat::sinks::fmt_slices (stlsoft::auto_buffer< C, N, A > & sink, int flags, size_t cchTotal, size_t numResults, ff_string_slice_t const * results) [inline]
Formats into an auto_buffer.
Because the auto_buffer does not provide any string-carrying semantics we need to define a strict protocol for the semantics of this function:
if the auto_buffer is empty, then the result is written to the given length, along with the line-terminator if required, and a terminating nul character is appended
if the auto_buffer is not empty, then the last character is examined and removed if it is the nul-terminator. Then the result is written, along with the line-terminator if required, and a terminating nul character is appended
Note:
For efficiency, this provides the weak exception guarantee, not the strong. IS THIS TRUE?!?!?!?
References fastformat::fastformat_getNewlineForPlatform(), fastformat::flags::ff_newLine, ff_string_slice_t::len, and ff_string_slice_t::ptr.
char_buffer_sink& fastformat::sinks::fmt_slices (char_buffer_sink & sink, int flags, size_t cchTotal, size_t numResults, ff_string_slice_t const * results) [inline]
Formats into a char_buffer.
References char_buffer_sink::write().
null_sink& fastformat::sinks::fmt_slices (null_sink & sink, int , size_t cchTotal, size_t numResults, ff_string_slice_t const * results) [inline]
Writes an array of string slices into a null_sink sink.
References null_sink::cchTotal, null_sink::numSlices, and null_sink::numWrites.
WindowsConsole_sink& fastformat::sinks::fmt_slices (WindowsConsole_sink & sink, int flags, size_t cchTotal, size_t numResults, ff_string_slice_t const * results) [inline]
Writes an array of string slices into a WindowsConsole_sink sink.
References WindowsConsole_sink::write().
std::basic_ostream<ff_char_t>& fastformat::sinks::fmt_slices (std::basic_ostream< ff_char_t > & sink, int flags, size_t cchTotal, size_t numResults, ff_string_slice_t const * results) [inline]
Writes an array of string slices into a std::ostream sink.
Note:
This sink always performs a concatenation, to avoid some atomicity problems in the output. If you are using string streams, instead include fastformat/sinks/stringstream.hpp to avoid this step, since it is unncessary in that case. If you are writing console output from multiple threads in a multi-threaded program, consider using instead C's streams library (i.e. stdout/stderr, via the FILE* sink
References fastformat::util::concat_slices(), fastformat::flags::ff_flush, and fastformat::flags::ff_newLine.
std::basic_stringstream<ff_char_t>& fastformat::sinks::fmt_slices (std::basic_stringstream< ff_char_t > & sink, int flags, size_t , size_t numResults, ff_string_slice_t const * results) [inline]
Writes an array of string slices into a std::stringstream sink.
References FASTFORMAT_LITERAL_STRING, fastformat::flags::ff_flush, fastformat::flags::ff_newLine, ff_string_slice_t::len, and ff_string_slice_t::ptr.
string_array_sink& fastformat::sinks::fmt_slices (string_array_sink & sink, int flags, size_t , size_t numResults, ff_string_slice_t const * results) [inline]
Writes an array of string slices into a string array sink.
References string_array_sink::write().
speech_sink& fastformat::sinks::fmt_slices (speech_sink & sink, int flags, size_t cchTotal, size_t numResults, ff_string_slice_t const * results) [inline]
Writes an array of string slices into a speech sink.
References speech_sink::write().
CString& fastformat::sinks::fmt_slices (CString & sink, int flags, size_t cchTotal, size_t numResults, ff_string_slice_t const * results) [inline]
Writes an array of string slices into a CString sink.
References fastformat::util::concat_slices(), fastformat::fastformat_getNewlineForPlatform(), fastformat::flags::ff_newLine, ff_string_slice_t::len, and ff_string_slice_t::ptr.
OutputDebugString_sink& fastformat::sinks::fmt_slices (OutputDebugString_sink & sink, int flags, size_t cchTotal, size_t numResults, ff_string_slice_t const * results) [inline]
Writes an array of string slices to Windows' OutputDebugString().
References OutputDebugString_sink::write().
CComBSTR& fastformat::sinks::fmt_slices (CComBSTR & sink, int flags, size_t cchTotal, size_t numResults, ff_string_slice_t const * results) [inline]
Writes an array of string slices into a CComBSTR sink.
References fastformat::util::concat_slices(), fastformat::fastformat_getNewlineForPlatform(), fastformat::flags::ff_newLine, ff_string_slice_t::len, and ff_string_slice_t::ptr.
ff_FILE_sink& fastformat::sinks::fmt_slices (ff_FILE_sink & sink, int flags, size_t cchTotal, size_t numResults, ff_string_slice_t const * results) [inline]
Writes an array of string slices into a ff_FILE_sink sink.
References fastformat::sinks::fmt_slices(), and ff_FILE_sink::stream.
FILE*& fastformat::sinks::fmt_slices (FILE *& sink, int flags, size_t cchTotal, size_t numResults, ff_string_slice_t const * results) [inline]
Writes an array of string slices into a FILE* sink.
Remarks:
Some C standard library implementations define standard stream variables via #define onto internal structures. Often in such cases it is not possible to pass the standard stream name - e.g. stdout - directly to a fmt() or write() function, since they need to be able to treat the sink argument as a mutating (non-const) reference. In such cases, the desired behaviour may be achieved by using the to_sink(FILE*) creator function, as in:
  ff::write(ff::to_sink(stderr), "oops!");
References fastformat::util::concat_slices(), FASTFORMAT_LITERAL_STRING, fastformat::flags::ff_flush, and fastformat::flags::ff_newLine.
WindowsMessageBox_sink fastformat::sinks::MessageBox (LPCTSTR caption, UINT type) [inline]
Creator function for the WindowsMessageBox_sink class.
WindowsMessageBox_sink fastformat::sinks::MessageBox (HWND hwnd, LPCTSTR caption, UINT type) [inline]
Creator function for the WindowsMessageBox_sink class.
WindowsConsole_sink fastformat::sinks::WindowsConsole (WORD textAttributes) [inline]
Creator function for the WindowsConsole_sink class.
WindowsConsole_sink fastformat::sinks::WindowsConsole (HANDLE hConsole, WORD textAttributes) [inline]
Creator function for the WindowsConsole_sink class.
FastFormat Library documentation Matthew Wilson, 2006-2015