Inserters
[The FastFormat (C++) Application Layer]
Inserter components, to allow explicit insertion of arbitrary types into FastFormat write()/fmt() statements.
Functions
ximpl_character::character_state ch (ff_char_t const &value)
Shorthand form of character() inserter function.
ximpl_character::character_state character (ff_char_t const &value)
Inserts the string form of a character value.
template<typename I >
ximpl_integer::ff_to_i_r_t_ integer (I const &value, int minimumWidth, int precision)
Inserts the string form of an integral value.
ximpl_integer::ff_to_i_r_t_ to_i (LARGE_INTEGER const &value, int minimumWidth=ximpl_integer::default_width_sentinel_(), int precision=ximpl_integer::default_precision_sentinel_())
Inserts the string form of a LARGE_INTEGER value.
stlsoft::basic_shim_string
< ff_char_t, 64 > real (double const &value)
[DEPRECATED] Inserts the string form of a floating-point value
stlsoft::basic_shim_string
< ff_char_t, 64 > real (double const &value, int minimumWidth, int decimalPlaces)
Inserts the string form of a floating-point value, with the given width and precision.
stlsoft::basic_shim_string
< ff_char_t, 64 > real (double const &value, int minimumWidth, int decimalPlaces, ff_char_t type)
Inserts the string form of a floating-point value, with the given width, precision and type.
stlsoft::basic_shim_string
< ff_char_t, 64 > to_e (double const &value)
Inserts the string form of a floating-point value.
stlsoft::basic_shim_string
< ff_char_t, 64 > to_E (double const &value)
Inserts the string form of a floating-point value.
stlsoft::basic_shim_string
< ff_char_t, 64 > to_e (double const &value, int minimumWidth, int decimalPlaces)
Inserts the string form of a floating-point value, with the given width and precision.
stlsoft::basic_shim_string
< ff_char_t, 64 > to_E (double const &value, int minimumWidth, int decimalPlaces)
Inserts the string form of a floating-point value, with the given width and precision.
stlsoft::basic_shim_string
< ff_char_t, 64 > to_f (double const &value)
Inserts the string form of a floating-point value.
stlsoft::basic_shim_string
< ff_char_t, 64 > to_f (double const &value, int minimumWidth, int decimalPlaces)
Inserts the string form of a floating-point value, with the given width and precision.
stlsoft::basic_shim_string
< ff_char_t, 64 > to_g (double const &value)
Inserts the string form of a floating-point value.
stlsoft::basic_shim_string
< ff_char_t, 64 > to_G (double const &value)
Inserts the string form of a floating-point value.
stlsoft::basic_shim_string
< ff_char_t, 64 > to_g (double const &value, int minimumWidth, int decimalPlaces)
Inserts the string form of a floating-point value, with the given width and precision.
stlsoft::basic_shim_string
< ff_char_t, 64 > to_G (double const &value, int minimumWidth, int decimalPlaces)
Inserts the string form of a floating-point value, with the given width and precision.
template<typename I >
ximpl_integer::ff_to_i_r_t_ to_i (I const &value)
Inserts the string form of an integral value.
template<typename I >
ximpl_integer::ff_to_i_r_t_ to_i (I const &value, int minimumWidth)
Inserts the string form of an integral value.
template<typename I >
ximpl_integer::ff_to_i_r_t_ to_i (I const &value, int minimumWidth, int precision)
Inserts the string form of an integral value.
template<typename I >
fastformat::inserters::ximpl_integer::ff_to_i_r_t_ to_i_null_if_not (I const &i, I const &sentinel)
Inserts the string form of an integral value, or an empty string in the case where the value is zero.
template<typename I >
fastformat::inserters::ximpl_integer::ff_to_i_r_t_ to_i_null_if_not (I const &i, I const &sentinel, int nullIfSame)
Inserts the string form of an integral value, or an empty string in the case where the value is zero if the parameter nullIfZero is non-zero.
template<typename I >
fastformat::inserters::ximpl_integer::ff_to_i_r_t_ to_i_null_if_zero (I const &i)
Inserts the string form of an integral value, or an empty string in the case where the value is zero.
template<typename I >
fastformat::inserters::ximpl_integer::ff_to_i_r_t_ to_i_null_if_zero (I const &i, int nullIfZero)
Inserts the string form of an integral value, or an empty string in the case where the value is zero if the parameter nullIfZero is non-zero.
template<typename I >
fastformat::inserters::ximpl_integer::ff_to_i_r_t_ to_i_null_if_0 (I const &i)
Pseudonym for to_i_null_if_zero()
template<typename I >
fastformat::inserters::ximpl_integer::ff_to_i_r_t_ to_i_null_if_0 (I const &i, int nullIfZero)
Pseudonym for to_i_null_if_zero()
template<typename I >
ximpl_integer::ff_to_i_r_t_ to_x (I const &value)
Inserts the hexadecimal string form of an integral value.
template<typename I >
ximpl_integer::ff_to_i_r_t_ to_X (I const &value)
Inserts the hexadecimal string form of an integral value.
template<typename I >
ximpl_integer::ff_to_i_r_t_ to_x (I const &value, int minimumWidth)
Inserts the hexadecimal string form of an integral value.
template<typename I >
ximpl_integer::ff_to_i_r_t_ to_X (I const &value, int minimumWidth)
Inserts the hexadecimal string form of an integral value.
template<typename I >
ximpl_integer::ff_to_i_r_t_ to_x (I const &value, int minimumWidth, int precision)
Inserts the hexadecimal string form of an integral value.
template<typename I >
ximpl_integer::ff_to_i_r_t_ to_X (I const &value, int minimumWidth, int precision)
Inserts the hexadecimal string form of an integral value.
ximpl_integer::ff_to_i_r_t_ to_i (ULARGE_INTEGER const &value, int minimumWidth=ximpl_integer::default_width_sentinel_(), int precision=ximpl_integer::default_precision_sentinel_())
Inserts the string form of a ULARGE_INTEGER value.
Detailed Description
Inserter components, to allow explicit insertion of arbitrary types into FastFormat write()/fmt() statements.
Function Documentation
ximpl_character::character_state fastformat::inserters::ch (ff_char_t const & value) [inline]
Shorthand form of character() inserter function.
Parameters:
value The character value to be inserted.
References fastformat::inserters::character().
ximpl_character::character_state fastformat::inserters::character (ff_char_t const & value) [inline]
Inserts the string form of a character value.
Parameters:
value The character value to be inserted.
Referenced by fastformat::inserters::ch().
ximpl_integer::ff_to_i_r_t_ fastformat::inserters::integer (I const & value, int minimumWidth, int precision) [inline]
Inserts the string form of an integral value.
Parameters:
value The integral value to be converted to string form
minimumWidth The minimum width of the result. If negative, the integer is aligned to the left of the resulting field
precision The minimum number of digits in the field, which will result in zero-padding if the given integer has fewer digits
Returns:
An instance of an insertable type containing the string form of the integer
Precondition:
abs(minimumWidth) < 512
decimalPlaces <= minimumWidth
stlsoft::basic_shim_string<ff_char_t, 64> fastformat::inserters::real (double const & value) [inline]
[DEPRECATED] Inserts the string form of a floating-point value
Parameters:
value The double value to be converted to string form
Deprecated:
Use to_f(), to_g(), or to_e() instead
Referenced by fastformat::inserters::to_E(), fastformat::inserters::to_e(), fastformat::inserters::to_f(), fastformat::inserters::to_G(), and fastformat::inserters::to_g().
stlsoft::basic_shim_string<ff_char_t, 64> fastformat::inserters::real (double const & value, int minimumWidth, int decimalPlaces) [inline]
Inserts the string form of a floating-point value, with the given width and precision.
Parameters:
value The double value to be converted to string form
minimumWidth The minimum width of the resulting string form. If non-negative, the result will be right-aligned. If negative, the result will be left-aligned
decimalPlaces The number of decimal places to be included
Precondition:
abs(minimumWidth) < 512
decimalPlaces <= abs(minimumWidth)
stlsoft::basic_shim_string<ff_char_t, 64> fastformat::inserters::real (double const & value, int minimumWidth, int decimalPlaces, ff_char_t type) [inline]
Inserts the string form of a floating-point value, with the given width, precision and type.
Parameters:
value The double value to be converted to string form
minimumWidth The minimum width of the resulting string form. If non-negative, the result will be right-aligned. If negative, the result will be left-aligned
decimalPlaces The number of decimal places to be included
type One of the following characters that denote the type of the floating-point representation: e, E, f, F, g, or G
Precondition:
abs(minimumWidth) < 512
decimalPlaces <= minimumWidth
stlsoft::basic_shim_string<ff_char_t, 64> fastformat::inserters::to_e (double const & value) [inline]
Inserts the string form of a floating-point value.
Parameters:
value The double value to be converted to string form
References fastformat::inserters::real().
stlsoft::basic_shim_string<ff_char_t, 64> fastformat::inserters::to_E (double const & value) [inline]
Inserts the string form of a floating-point value.
Parameters:
value The double value to be converted to string form
References fastformat::inserters::real().
stlsoft::basic_shim_string<ff_char_t, 64> fastformat::inserters::to_e (double const & value, int minimumWidth, int decimalPlaces) [inline]
Inserts the string form of a floating-point value, with the given width and precision.
Parameters:
value The double value to be converted to string form
minimumWidth The minimum width of the resulting string form
decimalPlaces The number of decimal places to be included
Precondition:
minimumWidth < 512
decimalPlaces <= minimumWidth
References fastformat::inserters::real().
stlsoft::basic_shim_string<ff_char_t, 64> fastformat::inserters::to_E (double const & value, int minimumWidth, int decimalPlaces) [inline]
Inserts the string form of a floating-point value, with the given width and precision.
Parameters:
value The double value to be converted to string form
minimumWidth The minimum width of the resulting string form
decimalPlaces The number of decimal places to be included
Precondition:
minimumWidth < 512
decimalPlaces <= minimumWidth
References fastformat::inserters::real().
stlsoft::basic_shim_string<ff_char_t, 64> fastformat::inserters::to_f (double const & value) [inline]
Inserts the string form of a floating-point value.
Parameters:
value The double value to be converted to string form
Examples:
examples/example.overload.3.floatingpoint_columns/example.overload.3.floatingpoint_columns.cpp.
References fastformat::inserters::real().
stlsoft::basic_shim_string<ff_char_t, 64> fastformat::inserters::to_f (double const & value, int minimumWidth, int decimalPlaces) [inline]
Inserts the string form of a floating-point value, with the given width and precision.
Parameters:
value The double value to be converted to string form
minimumWidth The minimum width of the resulting string form
decimalPlaces The number of decimal places to be included
Precondition:
minimumWidth < 512
decimalPlaces <= minimumWidth
References fastformat::inserters::real().
stlsoft::basic_shim_string<ff_char_t, 64> fastformat::inserters::to_g (double const & value, int minimumWidth, int decimalPlaces) [inline]
Inserts the string form of a floating-point value, with the given width and precision.
Parameters:
value The double value to be converted to string form
minimumWidth The minimum width of the resulting string form
decimalPlaces The number of decimal places to be included
Precondition:
minimumWidth < 512
decimalPlaces <= minimumWidth
References fastformat::inserters::real().
stlsoft::basic_shim_string<ff_char_t, 64> fastformat::inserters::to_G (double const & value, int minimumWidth, int decimalPlaces) [inline]
Inserts the string form of a floating-point value, with the given width and precision.
Parameters:
value The double value to be converted to string form
minimumWidth The minimum width of the resulting string form
decimalPlaces The number of decimal places to be included
Precondition:
minimumWidth < 512
decimalPlaces <= minimumWidth
References fastformat::inserters::real().
stlsoft::basic_shim_string<ff_char_t, 64> fastformat::inserters::to_g (double const & value) [inline]
Inserts the string form of a floating-point value.
Parameters:
value The double value to be converted to string form
References fastformat::inserters::real().
stlsoft::basic_shim_string<ff_char_t, 64> fastformat::inserters::to_G (double const & value) [inline]
Inserts the string form of a floating-point value.
Parameters:
value The double value to be converted to string form
References fastformat::inserters::real().
ximpl_integer::ff_to_i_r_t_ fastformat::inserters::to_i (LARGE_INTEGER const & value, int minimumWidth = ximpl_integer::default_width_sentinel_(), int precision = ximpl_integer::default_precision_sentinel_()) [inline]
Inserts the string form of a LARGE_INTEGER value.
Parameters:
value The LARGE_INTEGER value to be converted to string form
minimumWidth The minimum width of the result. If negative, the integer is aligned to the left of the resulting field
precision The minimum number of digits in the field, which will result in zero-padding if the given integer has fewer digits
Returns:
An instance of an insertable type containing the string form of the integer
Precondition:
abs(minimumWidth) < 512
decimalPlaces <= minimumWidth
Referenced by fastformat::inserters::to_i(), fastformat::inserters::to_i_null_if_not(), and fastformat::inserters::to_i_null_if_zero().
ximpl_integer::ff_to_i_r_t_ fastformat::inserters::to_i (I const & value) [inline]
Inserts the string form of an integral value.
Parameters:
value The integral value to be converted to string form
Returns:
An instance of an insertable type containing the string form of the integer
Precondition:
I is an integral type
ximpl_integer::ff_to_i_r_t_ fastformat::inserters::to_i (I const & value, int minimumWidth) [inline]
Inserts the string form of an integral value.
Parameters:
value The integral value to be converted to string form
minimumWidth The minimum width of the result. If negative, the integer is aligned to the left of the resulting field
Returns:
An instance of an insertable type containing the string form of the integer
Precondition:
I is an integral type
abs(minimumWidth) < 512
ximpl_integer::ff_to_i_r_t_ fastformat::inserters::to_i (ULARGE_INTEGER const & value, int minimumWidth = ximpl_integer::default_width_sentinel_(), int precision = ximpl_integer::default_precision_sentinel_()) [inline]
Inserts the string form of a ULARGE_INTEGER value.
Parameters:
value The ULARGE_INTEGER value to be converted to string form
minimumWidth The minimum width of the result. If negative, the integer is aligned to the left of the resulting field
precision The minimum number of digits in the field, which will result in zero-padding if the given integer has fewer digits
Returns:
An instance of an insertable type containing the string form of the integer
Precondition:
abs(minimumWidth) < 512
decimalPlaces <= minimumWidth
References fastformat::inserters::to_i().
ximpl_integer::ff_to_i_r_t_ fastformat::inserters::to_i (I const & value, int minimumWidth, int precision) [inline]
Inserts the string form of an integral value.
Parameters:
value The integral value to be converted to string form
minimumWidth The minimum width of the result. If negative, the integer is aligned to the left of the resulting field
precision The minimum number of digits in the field, which will result in zero-padding if the given integer has fewer digits
Returns:
An instance of an insertable type containing the string form of the integer
Precondition:
I is an integral type
abs(minimumWidth) < 512
decimalPlaces <= minimumWidth
fastformat::inserters::ximpl_integer::ff_to_i_r_t_ fastformat::inserters::to_i_null_if_0 (I const & i)
Pseudonym for to_i_null_if_zero()
References fastformat::inserters::to_i_null_if_zero().
fastformat::inserters::ximpl_integer::ff_to_i_r_t_ fastformat::inserters::to_i_null_if_0 (I const & i, int nullIfZero)
Pseudonym for to_i_null_if_zero()
References fastformat::inserters::to_i_null_if_zero().
fastformat::inserters::ximpl_integer::ff_to_i_r_t_ fastformat::inserters::to_i_null_if_not (I const & i, I const & sentinel, int nullIfSame)
Inserts the string form of an integral value, or an empty string in the case where the value is zero if the parameter nullIfZero is non-zero.
Parameters:
i The integral value to be converted to string form.
sentinel The value to which i will be compared for exclusion.
nullIfSame Causes a "0" to be replaced by the empty string
Returns:
An instance of an insertable type containing the string form of the integer
Precondition:
I is an integral type
References fastformat::inserters::to_i().
fastformat::inserters::ximpl_integer::ff_to_i_r_t_ fastformat::inserters::to_i_null_if_not (I const & i, I const & sentinel)
Inserts the string form of an integral value, or an empty string in the case where the value is zero.
Parameters:
i The integral value to be converted to string form.
sentinel The value to which i will be compared for exclusion.
Returns:
An instance of an insertable type containing the string form of the integer
Precondition:
I is an integral type
References fastformat::inserters::to_i().
fastformat::inserters::ximpl_integer::ff_to_i_r_t_ fastformat::inserters::to_i_null_if_zero (I const & i, int nullIfZero)
Inserts the string form of an integral value, or an empty string in the case where the value is zero if the parameter nullIfZero is non-zero.
Parameters:
i The integral value to be converted to string form
nullIfZero Causes a "0" to be replaced by the empty string
Returns:
An instance of an insertable type containing the string form of the integer
Precondition:
I is an integral type
References fastformat::inserters::to_i().
fastformat::inserters::ximpl_integer::ff_to_i_r_t_ fastformat::inserters::to_i_null_if_zero (I const & i)
Inserts the string form of an integral value, or an empty string in the case where the value is zero.
Parameters:
i The integral value to be converted to string form
Returns:
An instance of an insertable type containing the string form of the integer
Precondition:
I is an integral type
References fastformat::inserters::to_i().
Referenced by fastformat::inserters::to_i_null_if_0().
ximpl_integer::ff_to_i_r_t_ fastformat::inserters::to_x (I const & value, int minimumWidth, int precision) [inline]
Inserts the hexadecimal string form of an integral value.
Parameters:
value The integral value to be converted to hexadecimal string form
minimumWidth The minimum width of the result. If negative, the integer is aligned to the left of the resulting field
precision The minimum number of digits in the field, which will result in zero-padding if the given integer has fewer digits
Returns:
An instance of an insertable type containing the string form of the integer
Precondition:
I is an integral type
abs(minimumWidth) < 512
decimalPlaces <= minimumWidth
ximpl_integer::ff_to_i_r_t_ fastformat::inserters::to_X (I const & value, int minimumWidth, int precision) [inline]
Inserts the hexadecimal string form of an integral value.
Parameters:
value The integral value to be converted to hexadecimal string form
minimumWidth The minimum width of the result. If negative, the integer is aligned to the left of the resulting field
precision The minimum number of digits in the field, which will result in zero-padding if the given integer has fewer digits
Returns:
An instance of an insertable type containing the string form of the integer
Precondition:
I is an integral type
abs(minimumWidth) < 512
decimalPlaces <= minimumWidth
ximpl_integer::ff_to_i_r_t_ fastformat::inserters::to_X (I const & value, int minimumWidth) [inline]
Inserts the hexadecimal string form of an integral value.
Parameters:
value The integral value to be converted to hexadecimal string form
minimumWidth The minimum width of the result. If negative, the integer is aligned to the left of the resulting field
Returns:
An instance of an insertable type containing the string form of the integer
Precondition:
I is an integral type
abs(minimumWidth) < 512
ximpl_integer::ff_to_i_r_t_ fastformat::inserters::to_X (I const & value) [inline]
Inserts the hexadecimal string form of an integral value.
Parameters:
value The integral value to be converted to hexadecimal string form
Returns:
An instance of an insertable type containing the string form of the integer
Precondition:
I is an integral type
ximpl_integer::ff_to_i_r_t_ fastformat::inserters::to_x (I const & value) [inline]
Inserts the hexadecimal string form of an integral value.
Parameters:
value The integral value to be converted to hexadecimal string form
Returns:
An instance of an insertable type containing the string form of the integer
Precondition:
I is an integral type
ximpl_integer::ff_to_i_r_t_ fastformat::inserters::to_x (I const & value, int minimumWidth) [inline]
Inserts the hexadecimal string form of an integral value.
Parameters:
value The integral value to be converted to hexadecimal string form
minimumWidth The minimum width of the result. If negative, the integer is aligned to the left of the resulting field
Returns:
An instance of an insertable type containing the string form of the integer
Precondition:
I is an integral type
abs(minimumWidth) < 512
FastFormat Library documentation Matthew Wilson, 2006-2015