fastformat Namespace Reference
The FastFormat root namespace - fastformat.
Namespaces
namespace filters
Namespace within which FastFormat filtering conversion shim functions are defined.
namespace flags
Namespace within which FastFormat flag constants (of type int) are defined.
namespace internal
Namespace within which internal FastFormat types and functions are defined.
namespace iterators
Namespace within which FastFormat iterators are defined.
namespace sinks
Namespace within which FastFormat sink functions are defined.
namespace util
FastFormat utility namespace.
Classes
class openrj_bundle
A resource bundle that reads Open-RJ Jar files.
class properties_bundle
A resource bundle that reads properties files.
class windows_resource_bundle
A resource bundle that reads Windows INI files.
class winini_bundle
A resource bundle that reads Windows INI files.
class fastformat_exception
Root class for all FastFormat exception.
class format_parsing_exception
Root class for all format parsing exceptions.
class illformed_format_exception
Exception class that represents an illformed format string.
class mismatched_replacements_exception
Root class for all parameter replacement exceptions.
class missing_argument_exception
Exception class that represents the case where one or more replacement parameters are specified in the format string but no matching arguments are presented in the argument list.
class unreferenced_argument_exception
Exception class that represents the case where one or more arguments in the argument list are unreferenced in the format.
class bundle_exception
Root class for all bundle exceptions.
class sink_exception
Root class for all sink exceptions.
class sink_output_exception
Exception class that represents the case where a sink has failed to write its output.
struct ff_string_slice_t
Read-only string slice.
struct ff_illformed_handler_info_t
Structure returned from fastformat_getProcessIllformedHandler(), fastformat_setProcessIllformedHandler(), fastformat_getThreadIllformedHandler(), and fastformat_setThreadIllformedHandler().
struct ff_mismatched_handler_info_t
Structure returned from fastformat_getProcessMismatchedHandler(), fastformat_setProcessMismatchedHandler(), fastformat_getThreadMismatchedHandler(), and fastformat_setThreadMismatchedHandler().
class fastformat_initialiser
Schwarz Counter initialiser for the FastFormat library.
class ignore_missing_arguments_scope
Scoping class that suppresses the reporting of unreferenced arguments during its lifetime.
class ignore_unreferenced_arguments_scope
Scoping class that suppresses the reporting of unreferenced arguments during its lifetime.
class mismatched_arguments_scope_base
Base class for scoping classes that customise the behaviour in response to mismatched arguments.
struct ff_format_element_t
Format element.
Typedefs
typedef char ff_char_t
Character type used by the library.
typedef ff_string_slice_t string_slice_t
Equivalent to ff_string_slice_t.
typedef ff_format_element_t format_element_t
Equivalent to ff_format_element_t.
typedef ff_parse_code_t parse_code_t
Equivalent to ff_parse_code_t.
typedef ff_replacement_code_t replacement_code_t
Equivalent to ff_replacement_code_t.
typedef int(* fastformat_illformedHandler_t)(void *param, ff_parse_code_t code, ff_char_t const *format, size_t formatLen, size_t replacementIndex, ff_char_t const *defect, size_t defectLen, int parameterIndex, void *reserved0, size_t reserved1, void *reserved2)
Ill-formed format handler callback function.
typedef
fastformat_illformedHandler_t illformedHandler_t
Equivalent to fastformat_illformedHandler_t.
typedef ff_illformed_handler_info_t illformed_handler_info_t
Equivalent to ff_illformed_handler_info_t.
typedef int(* fastformat_mismatchedHandler_t)(void *param, ff_replacement_code_t code, size_t numParameters, int parameterIndex, ff_string_slice_t *slice, void *reserved0, size_t reserved1, void *reserved2)
Mismatched replacement index handler callback function.
typedef
fastformat_mismatchedHandler_t mismatchedHandler_t
Equivalent to fastformat_mismatchedHandler_t.
typedef
ff_mismatched_handler_info_t mismatched_handler_info_t
Equivalent to ff_mismatched_handler_info_t.
Enumerations
enum ff_parse_code_t {
FF_PARSECODE_SUCCESS = 0,
FF_PARSECODE_INCOMPLETEREPLACEMENT = 1,
FF_PARSECODE_INVALIDINDEX = 2
}
Represents format parsing conditions.
enum ff_replacement_code_t {
FF_REPLACEMENTCODE_SUCCESS = 0,
FF_REPLACEMENTCODE_MISSING_ARGUMENT = 1,
FF_REPLACEMENTCODE_UNREFERENCED_ARGUMENT = 2
}
Represents parameter replacement conditions.
Functions
int fastformat_init (void)
Initialises the FastFormat library.
void fastformat_uninit (void)
Uninitialises the FastFormat library.
ff_char_t const * fastformat_getInitCodeString (int code)
Returns a constant pointer to a non-NULL non-modifiable nul-terminated string representing the initialisation code.
size_t fastformat_getInitCodeStringLength (int code)
Returns the length of the string returned by fastformat_getInitCodeString().
int init ()
Equivalent to fastformat_init().
void uninit ()
Equivalent to fastformat_uninit().
ff_char_t const * getInitCodeString (int code)
Equivalent to fastformat_getInitCodeString().
size_t getInitCodeStringLength (int code)
Equivalent to fastformat_getInitCodeStringLength().
ff_illformed_handler_info_t fastformat_getProcessIllformedHandler (void)
Gets the ill-formed format handler for the calling process.
ff_illformed_handler_info_t fastformat_setProcessIllformedHandler (fastformat_illformedHandler_t handler, void *param)
Sets the ill-formed format handler for the calling process.
ff_illformed_handler_info_t fastformat_getThreadIllformedHandler (void)
Gets the ill-formed format handler for the calling thread.
ff_illformed_handler_info_t fastformat_setThreadIllformedHandler (fastformat_illformedHandler_t handler, void *param)
Sets the ill-formed format handler for the calling thread.
ff_illformed_handler_info_t fastformat_getDefaultIllformedHandler (void)
Gets the default ill-formed format handler.
ff_mismatched_handler_info_t fastformat_getProcessMismatchedHandler (void)
Gets the mismatched parameter handler for the calling process.
ff_mismatched_handler_info_t fastformat_setProcessMismatchedHandler (fastformat_mismatchedHandler_t handler, void *param)
Sets the mismatched parameter handler for the calling process.
ff_mismatched_handler_info_t fastformat_getThreadMismatchedHandler (void)
Gets the mismatched parameter handler for the calling thread.
ff_mismatched_handler_info_t fastformat_setThreadMismatchedHandler (fastformat_mismatchedHandler_t handler, void *param)
Sets the mismatched parameter handler for the calling thread.
ff_mismatched_handler_info_t fastformat_getDefaultMismatchedHandler (void)
Gets the default mismatched parameter handler.
size_t fastformat_calculateNumberOfRequiredReplacements (ff_char_t const *format, size_t cchFormat)
Calculates the exact number of replacements required for the given format.
unsigned fastformat_parseFormat (ff_char_t const *format, size_t cchFormat, ff_format_element_t *formatElements, size_t numFormatElements, fastformat_illformedHandler_t handler, void *param)
Parses a format string into an array of replacement element descriptors.
size_t fastformat_fillReplacements (ff_string_slice_t *resultElements, ff_format_element_t const *formatElements, size_t numElements, ff_string_slice_t const *arguments, size_t numArguments, fastformat_mismatchedHandler_t handler, void *param, size_t *pnumResultElements)
Takes a number of pattern and replacement elements and populates an array of result elements.
size_t fastformat_accumulateSliceLengths (size_t numSlices, ff_string_slice_t const *slices)
Calculates the total length of an array of string slices.
unsigned fastformat_lookupPattern (ff_char_t const *pattern, size_t cchPattern, ff_format_element_t const **elements)
Looks up the array of replacement element descriptors, corresponding to the given pattern, from the pattern cache.
ff_string_slice_t fastformat_getNewlineForPlatform (void)
Returns a slice representing the CR/LF combination for the current platform.
ff_illformed_handler_info_t getProcessIllformedHandler ()
Equivalent to fastformat_getProcessIllformedHandler().
ff_illformed_handler_info_t setProcessIllformedHandler (illformedHandler_t handler, void *param)
Equivalent to fastformat_setProcessIllformedHandler().
ff_illformed_handler_info_t getThreadIllformedHandler ()
Equivalent to fastformat_getThreadIllformedHandler().
ff_illformed_handler_info_t setThreadIllformedHandler (illformedHandler_t handler, void *param)
Equivalent to fastformat_setThreadIllformedHandler().
ff_mismatched_handler_info_t getProcessMismatchedHandler ()
Equivalent to fastformat_getProcessMismatchedHandler().
ff_mismatched_handler_info_t setProcessMismatchedHandler (mismatchedHandler_t handler, void *param)
Equivalent to fastformat_setProcessMismatchedHandler().
ff_mismatched_handler_info_t getThreadMismatchedHandler ()
Equivalent to fastformat_getThreadMismatchedHandler().
ff_mismatched_handler_info_t setThreadMismatchedHandler (mismatchedHandler_t handler, void *param)
Equivalent to fastformat_setThreadMismatchedHandler().
string_slice_t getNewlineForPlatform ()
Equivalent to fastformat_getNewlineForPlatform().
char const * c_str_data_a (ff_string_slice_t const &slice)
Returns a possibly non-nul-terminated non-NULL C-style string representing the slice.
ff_char_t const * c_str_data (ff_string_slice_t const &slice)
Returns a possibly non-nul-terminated non-NULL C-style string representing the slice.
size_t c_str_len_a (ff_string_slice_t const &slice)
Returns the number of characters in the length of the C-style string representing the slice.
size_t c_str_len (ff_string_slice_t const &slice)
Returns the number of characters in the length of the C-style string representing the slice.
template<typename T >
T & to_sink (T &sink)
[PROVISIONAL] Degenerate conversion shim for specifying a sink.
template<typename S >
S & flush (S &sink)
Flushes the given sink, by formatting an empty statement with the flag fastformat::flags::ff_flush.
Detailed Description
The FastFormat root namespace - fastformat.
This the the root namespace for FastFormat, and contains the C-API functions, along with appropriate type-defs
Typedef Documentation
typedef char ff_char_t
Character type used by the library.
This will be wchar_t if FASTFORMAT_USE_WIDE_STRINGS is defined, otherwise char.
Examples:
examples/example.arguments.character/example.arguments.character.cpp.
typedef ff_format_element_t format_element_t
Equivalent to ff_format_element_t.
typedef ff_illformed_handler_info_t illformed_handler_info_t
Equivalent to ff_illformed_handler_info_t.
typedef fastformat_illformedHandler_t illformedHandler_t
Equivalent to fastformat_illformedHandler_t.
typedef ff_mismatched_handler_info_t mismatched_handler_info_t
Equivalent to ff_mismatched_handler_info_t.
typedef fastformat_mismatchedHandler_t mismatchedHandler_t
Equivalent to fastformat_mismatchedHandler_t.
typedef ff_parse_code_t parse_code_t
Equivalent to ff_parse_code_t.
typedef ff_replacement_code_t replacement_code_t
Equivalent to ff_replacement_code_t.
typedef ff_string_slice_t string_slice_t
Equivalent to ff_string_slice_t.
Function Documentation
ff_char_t const* fastformat::c_str_data (ff_string_slice_t const & slice) [inline]
Returns a possibly non-nul-terminated non-NULL C-style string representing the slice.
References c_str_data_a().
char const* fastformat::c_str_data_a (ff_string_slice_t const & slice) [inline]
Returns a possibly non-nul-terminated non-NULL C-style string representing the slice.
Examples:
examples/example.overload.2.custom_type.string_access_shims/example.overload.2.custom_type.string_access_shims.cpp.
Referenced by c_str_data().
size_t fastformat::c_str_len (ff_string_slice_t const & slice) [inline]
Returns the number of characters in the length of the C-style string representing the slice.
References c_str_len_a().
Referenced by shim_string_sink::append().
size_t fastformat::c_str_len_a (ff_string_slice_t const & slice) [inline]
Returns the number of characters in the length of the C-style string representing the slice.
Examples:
examples/example.overload.2.custom_type.string_access_shims/example.overload.2.custom_type.string_access_shims.cpp.
Referenced by c_str_len().
ff_string_slice_t fastformat::fastformat_getNewlineForPlatform (void)
Returns a slice representing the CR/LF combination for the current platform.
Referenced by fastformat::sinks::fmt_slices(), getNewlineForPlatform(), WindowsConsole_sink::write(), vectored_file_sink::write(), string_array_sink::write(), OutputDebugString_sink::write(), char_buffer_sink::write(), and c_string_sink::write().
T& fastformat::to_sink (T & sink) [inline]
[PROVISIONAL] Degenerate conversion shim for specifying a sink.
Note:
This function is provisional, and may be subject to change in any pre-1.0 release.
FastFormat Library documentation Matthew Wilson, 2006-2015